apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kvrouters

resources:
  - ../../base
  - vllm-statefulset.yaml
  - workers-headless-service.yaml
  - servicemonitor.yaml

configMapGenerator:
  - name: kvrouters-config
    files:
      - router.yaml
